package com.project.spring.dao;

public class Queries {

	public final static String INSERT_INTO_FREELANCER = "INSERT INTO FREELANCER			\n"
			+ "         (                        \n"
			+ "                 FIRST_NAME   ,   \n"
			+ "                 LAST_NAME    ,   \n"
			+ "                 EMAIL        ,   \n"
			+ "                 PASSWORD     ,   \n"
			+ "                 PROFILE_IMAGE,   \n"
			+ "                 MOBILE       ,   \n"
			+ "                 LOCATION     ,   \n"
			+ "                 DESCRIPTION  ,   \n"
			+ "                 AGE          ,   \n"
			+ "                 CATEG_NAME       \n"
			+ "         )                        \n"
			+ " VALUES                           \n"
			+ "         (                        \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "					?                \n"
			+ "         )                        \n";

	public final static String INSERT_INTO_CLIENT = " INSERT INTO CLIENT					\n"
			+ "         (                           \n"
			+ "                 FIRST_NAME   ,      \n"
			+ "                 LAST_NAME    ,      \n"
			+ "                 EMAIL        ,      \n"
			+ "                 PASSWORD     ,      \n"
			+ "                 PROFILE_IMAGE,      \n"
			+ "                 AGE          ,      \n"
			+ "                 LOCATION     ,      \n"
			+ "                 DESCRIPTION  ,      \n"
			+ "                 MOBILE              \n"
			+ "         )                           \n"
			+ " VALUES                              \n"
			+ "         (                           \n"
			+ "                 ?,                  \n"
			+ "                 ?,                  \n"
			+ "                 ?,                  \n"
			+ "                 ?,                  \n"
			+ "                 ?,                  \n"
			+ "                 ?,                  \n"
			+ "                 ?,                  \n"
			+ "                 ?,                  \n"
			+ "                 ?                   \n"
			+ "         )							\n";

	public final static String GET_CLINET_BY_ID = "SELECT						\n "
			+ "        ID,		             	\n "
			+ "        USERROLE 		        \n "
			+ "FROM                          	\n "
			+ "        CLIENT                	\n "
			+ "WHERE                         	\n "
			+ "        EMAIL    = ?   	 		\n "
			+ "AND     PASSWORD = ?				\n ";

	public final static String GET_FREELNACER_BY_ID = " SELECT						\n"
			+ "         ID,                  \n"
			+ "         USERROLE             \n"
			+ " FROM                         \n"
			+ "         FREELANCER           \n"
			+ " WHERE                        \n"
			+ "         EMAIL = ?            \n"
			+ " AND 	PASSWORD = ?         \n";

	public final static String GET_ALL_REQUESTS = "SELECT						\n"
			+ "        r.id               		 ,    \n"
			+ "        r.title          	   	 ,    \n"
			+ "        r.dateposted      		 ,    \n"
			+ "        r.deadline         		 ,    \n"
			+ "        r.categ_name      		 ,    \n"
			+ "        r.location        		 ,    \n"
			+ "        r.description     		 ,    \n"
			+ "        r.image          		 ,    \n"
			+ "        r.price          		 ,    \n"
			+ "        r.status as request_status,    \n"
			+ "        c.id as client_id  		 ,    \n"
			+ "        c.first_name 		     ,    \n"
			+ "        c.last_name		         ,    \n"
			+ "        c.mobile  		         ,    \n"
			+ "        c.profile_image      		  \n"
			+ "FROM                          		  \n"
			+ "        requests r              		  \n"
			+ "JOIN                         		  \n"
			+ "        client c             		  \n"
			+ "ON                           		  \n"
			+ "        r.client_id = c.id   		  \n"
			+ "WHERE 								  \n"
			+ "        STATUS = 'Pending'             \n";
	public final static String CREATE_POST = " INSERT INTO POSTS				\n"
			+ "         (                        \n"
			+ "                 FREELANCER_ID,   \n"
			+ "                 TITLE        ,   \n"
			+ "                 DEADLINE     ,   \n"
			+ "                 LOCATION     ,   \n"
			+ "                 CATEG_NAME   ,   \n"
			+ "                 DESCRIPTION  ,   \n"
			+ "                 IMAGE        ,   \n"
			+ "                 PRICE            \n"
			+ "         )                        \n"
			+ " VALUES                           \n"
			+ "         (                        \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?,               \n"
			+ "                 ?                \n"
			+ "         )                        \n";

	public final static String GET_POSTS_BY_ID = " SELECT						\n"
			+ "         ID           ,       \n"
			+ "         FREELANCER_ID,       \n"
			+ "         TITLE        ,       \n"
			+ "         DATE_POSTED  ,       \n"
			+ "         DEADLINE     ,       \n"
			+ "         LOCATION     ,       \n"
			+ "         CATEG_NAME   ,       \n"
			+ "         DESCRIPTION  ,       \n"
			+ "         IMAGE        ,       \n"
			+ "         PRICE        ,       \n"
			+ "         STATUS               \n"
			+ " FROM                         \n"
			+ "         posts                \n"
			+ " WHERE                        \n"
			+ "      freelancer_id = ?       \n";

	public final static String UPDATE_REQUEST_STATUS = "UPDATE								\n"
			+ "        REQUESTS                      \n"
			+ "SET                                   \n"
			+ "        STATUS = ?                    \n"
			+ "WHERE                                 \n"
			+ "        ID = ?                        \n";

	public final static String INSERT_APPLIED_REQUEST = " INSERT INTO APPLIED_REQUESTS									\n"
			+ "         (                                                    \n"
			+ "                 CLIENT_ID    ,                               \n"
			+ "                 FREELANCER_ID,                               \n"
			+ "                 CATEG_NAME   ,                               \n"
			+ "                 DESCRIPTION  ,                               \n"
			+ "                 DATEPOSTED   ,                               \n"
			+ "                 DEADLINE     ,                               \n"
			+ "                 LOCATION     ,                               \n"
			+ "                 TITLE        ,                               \n"
			+ "                 PRICE        ,                               \n"
			+ "                 IMAGE        ,                               \n"
			+ "                 STATUS       ,                               \n"
			+ "                 request_id                                   \n"
			+ "         )                                                    \n"
			+ " SELECT                                                       \n"
			+ "         CLIENT_ID           ,                                \n"
			+ "         ? AS FREELANCER_ID  ,                                \n"
			+ "         CATEG_NAME          ,                                \n"
			+ "         TO_CHAR(DESCRIPTION),                                \n"
			+ "         DATEPOSTED          ,                                \n"
			+ "         DEADLINE            ,                                \n"
			+ "         LOCATION            ,                                \n"
			+ "         TITLE               ,                                \n"
			+ "         PRICE               ,                                \n"
			+ "         IMAGE               ,                                \n"
			+ "         ? AS STATUS       	,								 \n"
			+ "         id                                                   \n"
			+ " FROM                                                         \n"
			+ "         REQUESTS                                             \n"
			+ " WHERE                                                        \n"
			+ "         ID = ?                                               \n";

	public final static String GET_ALL_JOBS_BY_FREELANCER_ID = " SELECT												\n"
			+ "         t.id AS todo_id                ,             \n"
			+ "         t.freelancer_id                ,             \n"
			+ "         t.client_id                    ,             \n"
			+ "         t.status        AS todo_status        ,      \n"
			+ "         c.first_name    AS client_first_name  ,      \n"
			+ "         c.last_name     AS client_last_name   ,      \n"
			+ "         c.profile_image AS client_profileImage,      \n"
			+ "         c.mobile        AS clientMobile       ,      \n"
			+ "         r.id            AS appliedRequest_id  ,      \n"
			+ "         r.request_id    AS Request_id         ,      \n"
			+ "         r.title         AS request_title      ,      \n"
			+ "         r.description   AS request_description,      \n"
			+ "         r.deadline      AS request_deadLine   ,      \n"
			+ "         r.datePosted    AS request_datePosted ,      \n"
			+ "         r.categ_name    AS request_categ_name ,      \n"
			+ "         r.location      AS request_location   ,      \n"
			+ "         r.price         AS request_price      ,      \n"
			+ "         p.id            AS hiredPost_id       ,      \n"
			+ "         p.post_id       AS Post_id            ,      \n"
			+ "         p.title         AS post_title         ,      \n"
			+ "         p.description   AS post_description   ,      \n"
			+ "         p.deadline      AS post_deadLine      ,      \n"
			+ "         p.datePosted    AS post_datePosted    ,      \n"
			+ "         p.categ_name    AS post_categ_name    ,      \n"
			+ "         p.location      AS post_location      ,      \n"
			+ "         p.price         AS post_price                \n"
			+ " FROM                                                 \n"
			+ "         ToDo t                                       \n"
			+ " LEFT JOIN                                            \n"
			+ "         client c                                     \n"
			+ " ON                                                   \n"
			+ "         t.client_id = c.id                           \n"
			+ " LEFT JOIN                                            \n"
			+ "         applied_requests r                           \n"
			+ " ON                                                   \n"
			+ "         t.applied_request_id = r.id                  \n"
			+ " LEFT JOIN                                            \n"
			+ "         hired_posts p                                \n"
			+ " ON                                                   \n"
			+ "         t.hired_post_id = p.id                       \n"
			+ " WHERE                                                \n"
			+ "         t.freelancer_id = ?                          \n"
			+ " AND     t.status        = 'onGoing'                  \n";

	public final static String GET_ALL_POSTS = "select												\n"
			+ "        p.id                       ,                  \n"
			+ "        p.title                    ,                  \n"
			+ "        p.date_posted              ,                  \n"
			+ "        p.deadline                 ,                  \n"
			+ "        p.location                 ,                  \n"
			+ "        p.categ_name               ,                  \n"
			+ "        p.Description              ,                  \n"
			+ "        p.image                    ,                  \n"
			+ "        p.price                    ,                  \n"
			+ "        p.status                   ,                  \n"
			+ "        f.id            as freelancer_id      ,       \n"
			+ "        f.first_name    as freelancerFirstName,       \n"
			+ "        f.last_name     as freelancerLastName ,       \n"
			+ "        f.mobile        as freelancerMobile   ,       \n"
			+ "        f.profile_image as freelancerProfileImage     \n"
			+ "from                                                  \n"
			+ "        posts p                                       \n"
			+ "join                                                  \n"
			+ "        freelancer f                                  \n"
			+ "on                                                    \n"
			+ "        p.freelancer_id = f.id                        \n";

	public final static String CREATE_REQUEST = "INSERT INTO REQUESTS			\n"
			+ "        (                     \n"
			+ "                CLIENT_ID   , \n"
			+ "                CATEG_NAME  , \n"
			+ "                DESCRIPTION , \n"
			+ "                DEADLINE    , \n"
			+ "                LOCATION    , \n"
			+ "                TITLE       , \n"
			+ "                PRICE       , \n"
			+ "                IMAGE         \n"
			+ "        )                     \n"
			+ "VALUES                        \n"
			+ "        (                     \n"
			+ "                ?,            \n"
			+ "                ?,            \n"
			+ "                ?,            \n"
			+ "                ?,            \n"
			+ "                ?,            \n"
			+ "                ?,            \n"
			+ "                ?,            \n"
			+ "                ?             \n"
			+ "        )                     \n";

	public final static String UPDATE_POST_STATUS = " UPDATE							\n"
			+ "         POSTS                    \n"
			+ " SET                              \n"
			+ "         STATUS = ?               \n"
			+ " WHERE                            \n"
			+ "         ID = ?                   \n";

	public final static String INSERT_HIRED_POSTS = "INSERT INTO HIRED_POSTS			\n"
			+ "        (                         \n"
			+ "                FREELANCER_ID,    \n"
			+ "                CLIENT_ID    ,    \n"
			+ "                CATEG_NAME   ,    \n"
			+ "                DESCRIPTION  ,    \n"
			+ "                DATEPOSTED   ,    \n"
			+ "                DEADLINE     ,    \n"
			+ "                LOCATION     ,    \n"
			+ "                TITLE        ,    \n"
			+ "                PRICE        ,    \n"
			+ "                IMAGE        ,    \n"
			+ "                STATUS       ,    \n"
			+ "                post_id           \n"
			+ "        )                         \n"
			+ "SELECT                            \n"
			+ "        FREELANCER_ID       ,     \n"
			+ "        ? AS CLIENT_ID      ,     \n"
			+ "        CATEG_NAME          ,     \n"
			+ "        TO_CHAR(DESCRIPTION),     \n"
			+ "        DATE_POSTED          ,    \n"
			+ "        DEADLINE            ,     \n"
			+ "        LOCATION            ,     \n"
			+ "        TITLE               ,     \n"
			+ "        PRICE               ,     \n"
			+ "        IMAGE               ,     \n"
			+ "        ? AS STATUS         ,     \n"
			+ "        id                        \n"
			+ "FROM                              \n"
			+ "        POSTS                  	 \n"
			+ "WHERE                             \n"
			+ "        ID = ?					 \n";

	public final static String GET_REQUESTS_BY_CLIENTID = " SELECT									\n"
			+ "         ID          ,                    \n"
			+ "         CLIENT_ID   ,                    \n"
			+ "         TITLE       ,                    \n"
			+ "         DATEPOSTED  ,                    \n"
			+ "         DEADLINE    ,                    \n"
			+ "         LOCATION    ,                    \n"
			+ "         CATEG_NAME  ,                    \n"
			+ "         DESCRIPTION ,                    \n"
			+ "         IMAGE       ,                    \n"
			+ "         PRICE       ,                    \n"
			+ "         STATUS                           \n"
			+ " FROM                                     \n"
			+ "         REQUESTS                         \n"
			+ " WHERE                                    \n"
			+ "         CLIENT_ID = ?                    \n";
	public final static String GET_PENDING_HIRED_POSTS_BY_CIENTID = " SELECT												\n"
			+ "         h.id                        ,                \n"
			+ "         h.title                     ,                \n"
			+ "         h.dateposted                ,                \n"
			+ "         h.deadline                  ,                \n"
			+ "         h.categ_name                ,                \n"
			+ "         h.location                  ,                \n"
			+ "         h.description               ,                \n"
			+ "         h.image                     ,                \n"
			+ "         h.status                    ,                \n"
			+ "         h.post_id                   ,                \n"
			+ "         h.price                     ,                \n"
			+ "         f.id            as freelancer_id       ,     \n"
			+ "         f.first_name    as freelancerFirstName ,     \n"
			+ "         f.last_name     as freelancerLastName  ,     \n"
			+ "         f.profile_image as freelancerProfileImage,   \n"
			+ "         f.mobile        as freelancerMobile          \n"
			+ " FROM                                                 \n"
			+ "         hired_posts h                                \n"
			+ " JOIN                                                 \n"
			+ "         freelancer f                                 \n"
			+ " ON                                                   \n"
			+ "         h.freelancer_id = f.id                       \n"
			+ " where                                                \n"
			+ "         client_id = ?                                \n";

	public final static String GET_PENDING_APPLIED_REQUESTS_BY_CLIENTID = " SELECT												\n"
			+ "         a.id                        ,                \n"
			+ "         a.title                     ,                \n"
			+ "         a.dateposted                ,                \n"
			+ "         a.deadline                  ,                \n"
			+ "         a.categ_name                ,                \n"
			+ "         a.location                  ,                \n"
			+ "         a.description               ,                \n"
			+ "         a.image                     ,                \n"
			+ "         a.status                    ,                \n"
			+ "         a.request_id                ,                \n"
			+ "         a.price                     ,                \n"
			+ "         f.id            as freelancer_id       ,     \n"
			+ "         f.first_name    as freelancerFirstName ,     \n"
			+ "         f.last_name     as freelancerLastName  ,     \n"
			+ "         f.profile_image as freelancerProfileImage,   \n"
			+ "         f.mobile        as freelancerMobile          \n"
			+ " FROM                                                 \n"
			+ "         applied_requests a                           \n"
			+ " JOIN                                                 \n"
			+ "         freelancer f                                 \n"
			+ " ON                                                   \n"
			+ "         a.freelancer_id = f.id                       \n"
			+ " where                                                \n"
			+ "         client_id = ?                                \n";

	public final static String INSERT_APPLIED_REQUEST_INTO_TODO = " INSERT INTO todo								\n"
			+ "         (                                    \n"
			+ "                 freelancer_id     ,          \n"
			+ "                 client_id         ,          \n"
			+ "                 status            ,          \n"
			+ "                 applied_request_id,          \n"
			+ "                 hired_post_id                \n"
			+ "         )                                    \n"
			+ " SELECT                                       \n"
			+ "         freelancer_id                    ,   \n"
			+ "         client_id                        ,   \n"
			+ "         	?	    AS status            ,   \n"
			+ "         a.id        AS applied_request_id,   \n"
			+ "         NULL        AS hired_post_id         \n"
			+ " FROM                                         \n"
			+ "         applied_requests a                   \n"
			+ " WHERE                                        \n"
			+ "         a.id = ?                             \n";

	public final static String UPDATE_APPLIED_REQUEST_STATUS = " update									\n"
			+ "         applied_requests                 \n"
			+ " set                                      \n"
			+ "         status = ?                       \n"
			+ " where                                    \n"
			+ "         id = ?                           \n";

	public final static String GET_PENDING_APPLIED_REQUESTS_BY_FREELANCERID = " SELECT											\n"
			+ "         a.id                        ,            \n"
			+ "         a.title                     ,            \n"
			+ "         a.dateposted                ,            \n"
			+ "         a.deadline                  ,            \n"
			+ "         a.categ_name                ,            \n"
			+ "         a.location                  ,            \n"
			+ "         a.description               ,            \n"
			+ "         a.image                     ,            \n"
			+ "         a.price                     ,            \n"
			+ "         a.status                    ,            \n"
			+ "         a.request_id                ,            \n"
			+ "         c.id            as client_id       ,     \n"
			+ "         c.first_name    as clientFirstName ,     \n"
			+ "         c.last_name     as clientLastName  ,     \n"
			+ "         c.profile_image as clientProfileImage,   \n"
			+ "         c.mobile        as clientMobile          \n"
			+ " FROM                                             \n"
			+ "         applied_requests a                       \n"
			+ " JOIN                                             \n"
			+ "         client c                                 \n"
			+ " ON                                               \n"
			+ "         a.client_id = c.id                       \n"
			+ " where                                            \n"
			+ "         freelancer_id = ?                        \n";

	public final static String GET_PENDING_HIRED_POSTS_BY_FREELANCERID = " SELECT											\n"
			+ "         h.id                        ,            \n"
			+ "         h.title                     ,            \n"
			+ "         h.dateposted                ,            \n"
			+ "         h.deadline                  ,            \n"
			+ "         h.categ_name                ,            \n"
			+ "         h.location                  ,            \n"
			+ "         h.description               ,            \n"
			+ "         h.image                     ,            \n"
			+ "         h.price                     ,            \n"
			+ "         h.status                    ,            \n"
			+ "         c.id            as client_id       ,     \n"
			+ "         c.first_name    as clientFirstName ,     \n"
			+ "         c.last_name     as clientLastName  ,     \n"
			+ "         c.profile_image as clientProfileImage,   \n"
			+ "         c.mobile        as clientMobile          \n"
			+ " FROM                                             \n"
			+ "         hired_posts h                            \n"
			+ " JOIN                                             \n"
			+ "         client c                                 \n"
			+ " ON                                               \n"
			+ "         h.client_id = c.id                       \n"
			+ " where                                            \n"
			+ "         freelancer_id = ?                        \n";

	public final static String INSERT_HIRED_POSTS_INTO_TODO = " INSERT INTO todo 					\n"
			+ "         (                            \n"
			+ "                 freelancer_id     ,  \n"
			+ "                 client_id         ,  \n"
			+ "                 status            ,  \n"
			+ "                 hired_post_id     ,  \n"
			+ "                 applied_request_id   \n"
			+ "         )                            \n"
			+ " SELECT                               \n"
			+ "         freelancer_id     ,          \n"
			+ "         client_id         ,          \n"
			+ "         ?    AS status       ,       \n"
			+ "         h.id AS hired_post_id,       \n"
			+ "         NULL AS applied_request_id   \n"
			+ " FROM                                 \n"
			+ "         hired_posts h                \n"
			+ " WHERE                                \n"
			+ "         h.id = ?                     \n";

	public final static String UPDATE_HIRED_POST_STATUS = " update						\n"
			+ "         hired_posts  		\n"
			+ " set                  		\n"
			+ "         status = ?   		\n"
			+ " where                		\n"
			+ "         id = ?       		\n";

	public final static String GET_FREELANCER_INFO_BY_ID = " SELECT 							\n"
			+ " 		id,             			\n"
			+ " 		first_name,     			\n"
			+ " 		last_name,      			\n"
			+ " 		email,          			\n"
			+ " 		password,       			\n"
			+ " 		age,            			\n"
			+ " 		categ_name,     			\n"
			+ " 		mobile,         			\n"
			+ " 		location,       			\n"
			+ " 		profile_image,  			\n"
			+ " 		description     			\n"
			+ " FROM                 				\n"
			+ " 		freelancer      			\n"
			+ " WHERE                				\n"
			+ " 		id = ?          			\n";

	public final static String GET_CLIENT_INFO_BY_ID = " SELECT								\n"
			+ "         id         ,                 	\n"
			+ "         first_name ,                 	\n"
			+ "         last_name  ,                 	\n"
			+ "         email ,                      	\n"
			+ " 		password    ,                   \n"
			+ " 		age         ,                   \n"
			+ " 		mobile      ,                   \n"
			+ " 		description ,                   \n"
			+ " 		location    ,                   \n"
			+ " 		profile_image                   \n"
			+ " FROM                                 	\n"
			+ "         client                       	\n"
			+ " where                                	\n"
			+ "         id = ?                       	\n";

	public final static String UPDATE_CLIENT_INFO_BY_ID = " UPDATE										\n"
			+ "         client                               	\n"
			+ " SET                                          	\n"
			+ "         	first_name 		= ? 		,       \n"
			+ "         	last_name  		= ? 		,       \n"
			+ "         	email      		= ? 		,       \n"
			+ " 			mobile        	= ?        	,       \n"
			+ " 			description  	= ?        	,       \n"
			+ " 			age        		= ?         ,       \n"
			+ " 			location  		= ?                 \n"
			+ " WHERE                                        	\n"
			+ " 			id = ?                 				\n";
	public final static String UPDATE_PROFILE_IMAGE_FOR_CLIENT = " UPDATE											\n"
			+ "         client                                   \n"
			+ " SET                                              \n"
			+ "         PROFILE_IMAGE = ?                        \n"
			+ " WHERE                                            \n"
			+ "         id = ?                                   \n";

	public final static String UPDATE_FREELANCER_INFO_BY_ID = " UPDATE										\n"
			+ "         freelancer                           	\n"
			+ " SET                                          	\n"
			+ "         	first_name 		= ? 		,       \n"
			+ "         	last_name  		= ? 		,       \n"
			+ "         	email      		= ? 		,       \n"
			+ " 			mobile        	= ?        	,       \n"
			+ " 			location        = ?        	,       \n"
			+ " 			categ_name      = ?        	,       \n"
			+ " 			description  	= ?        	,       \n"
			+ " 			age        		= ?                 \n"
			+ " WHERE                                        	\n"
			+ " 			id = ?                          	\n";

	public final static String UPDATE_PROFILE_IMAGE_FOR_FREELANCER = " UPDATE											\n"
			+ "         freelancer                               \n"
			+ " SET                                              \n"
			+ "         profile_image = ?                        \n"
			+ " WHERE                                            \n"
			+ "         id = ?                                   \n";
	public final static String INSERT_FINISHED_TASKS_INTO_FINISHED_TASKS_TABLE = " INSERT INTO FINISHEDTASKS				\n"
			+ "         (                                \n"
			+ "                 freelancer_id ,          \n"
			+ "                 client_id     ,          \n"
			+ "                 toDo_id                  \n"
			+ "         )                                \n"
			+ " SELECT                                   \n"
			+ "         t.freelancer_id ,                \n"
			+ "         t.client_id     ,                \n"
			+ "         t.id as toDo_id                  \n"
			+ " FROM                                     \n"
			+ "         todo t                           \n"
			+ " WHERE                                    \n"
			+ "         t.id = ?                         \n";

	public final static String UPDATE_STATUS_IN_TODO_TABLE = " update							\n"
			+ "         todo                     \n"
			+ " set                              \n"
			+ "         status = ?               \n"
			+ " where                            \n"
			+ "         id = ?                   \n";

	public final static String UPDATE_STATUS_IN_TODO_TABLE_FOR_CANCELING = " update							\n"
			+ "         todo                     \n"
			+ " set                              \n"
			+ "         status = ?               \n"
			+ " where                            \n"
			+ "         id = ?                   \n";

	public final static String DELETE_POST_BY_POST_ID = " DELETE										\n"
			+ " from                         				\n"
			+ "         posts                				\n"
			+ " where                        				\n"
			+ "         id = ?               				\n";

	public final static String DELETE_REQUEST_BY_REQUEST_ID = " DELETE										\n"
			+ " from                         				\n"
			+ "         requests              				\n"
			+ " where                        				\n"
			+ "         id = ?               				\n";

	public final static String DELETE_APPLIED_REQUEST_BY_ID = " DELETE										\n"
			+ " from                                         \n"
			+ "         applied_requests                     \n"
			+ " where                                        \n"
			+ "         id = ?                               \n";
	public final static String UPDATE_STATUS_AS_PENDING_IN_REQUESTS_TABLE = " UPDATE										\n"
			+ "         requests                             \n"
			+ " set                                          \n"
			+ "         status = ?                           \n"
			+ " where                                        \n"
			+ "         id = ?                               \n";
	public final static String DELETE_HIRED_POST_BY_ID = " DELETE										\n"
			+ " from                                         \n"
			+ "         hired_posts		                     \n"
			+ " where                                        \n"
			+ "         id = ?                               \n";

	public final static String UPDATE_STATUS_AS_PENDING_IN_POSTS_TABLE = " UPDATE										\n"
			+ "         posts                                \n"
			+ " set                                          \n"
			+ "         status = ?                           \n"
			+ " where                                        \n"
			+ "         id = ?                               \n";
	public final static String UPDATE_STATUS_IN_HIRED_POST_BY_POST_ID = " Update						                 \n"
			+ "         hired_posts		                     \n"
			+ " Set		                                     \n"
			+ "         status = ?		                     \n"
			+ " where                                        \n"
			+ "         post_id = ?                          \n";
	public final static String DELETE_APPLIED_REQUEST_BY_REQUEST_ID = " DELETE										\n"
			+ " from                                         \n"
			+ "         applied_requests                     \n"
			+ " where                                        \n"
			+ "         request_id = ?                       \n";
	public final static String INSERT_NEW_RECORDE_RATE_FOR_FREELANCER = "insert into ratings								\n"
			+ "        (                                         \n"
			+ "                freelancer_id,                    \n"
			+ "                client_id    ,                    \n"
			+ "                rate         ,                    \n"
			+ "                feedback                          \n"
			+ "        )                                         \n"
			+ "values                                            \n"
			+ "        (                                         \n"
			+ "                ?,                                \n"
			+ "                ?,                                \n"
			+ "                ?,                                \n"
			+ "                ?                                 \n"
			+ "        )                                         \n";
	public final static String GET_RATES_AND_COMMENTS_FOR_FREELANCER = "select									\n"
			+ "        rate,                             \n"
			+ "        feedback                          \n"
			+ "from                                      \n"
			+ "        ratings                           \n"
			+ "where                                     \n"
			+ "        freelancer_id = ?                 \n";
}